# Generated by Django 5.1.15 on 2026-07-30 09:59

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория проекта',
                'verbose_name_plural': 'Категории проектов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(help_text='Используется в адресе страницы, например: tsum-bishkek', max_length=220, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(help_text='Показывается в карточке на лендинге и в каталоге, до 200 символов', max_length=200, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, help_text='Показывается на детальной странице проекта', verbose_name='Полное описание')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год реализации')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Заказчик')),
                ('equipment', models.CharField(blank=True, help_text='Например: 6 лифтов Schindler 3300, 12 остановок', max_length=300, verbose_name='Оборудование')),
                ('cover', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='projects/covers/', verbose_name='Обложка')),
                ('is_published', models.BooleanField(default=False, help_text='Пока не отмечено — проект не виден на сайте', verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='projects.projectcategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='projects/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Фото проекта',
                'verbose_name_plural': 'Фото проекта',
                'ordering': ['order'],
            },
        ),
    ]
