# Generated by Django 5.1.15 on 2026-07-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_ky',
            field=models.TextField(blank=True, help_text='Показывается на детальной странице проекта', null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(blank=True, help_text='Показывается на детальной странице проекта', null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_ky',
            field=models.CharField(help_text='Показывается в карточке на лендинге и в каталоге, до 200 символов', max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_ru',
            field=models.CharField(help_text='Показывается в карточке на лендинге и в каталоге, до 200 символов', max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
