# Generated by Django 5.1.15 on 2026-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='В международном формате, например: +996700123456', max_length=20, verbose_name='Телефон (для ссылки tel:)')),
                ('phone_display', models.CharField(blank=True, help_text='Как показывать на сайте, например: +996 700 123 456', max_length=30, verbose_name='Телефон (для отображения)')),
                ('whatsapp', models.URLField(blank=True, help_text='Например: https://wa.me/996700123456', verbose_name='Ссылка WhatsApp')),
                ('telegram', models.URLField(blank=True, help_text='Например: https://t.me/unilift', verbose_name='Ссылка Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('address_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('address_ky', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('work_hours', models.CharField(blank=True, default='Пн–Сб 09:00–18:00', max_length=200, verbose_name='Часы работы')),
                ('work_hours_ru', models.CharField(blank=True, default='Пн–Сб 09:00–18:00', max_length=200, null=True, verbose_name='Часы работы')),
                ('work_hours_ky', models.CharField(blank=True, default='Пн–Сб 09:00–18:00', max_length=200, null=True, verbose_name='Часы работы')),
                ('map_url', models.URLField(blank=True, help_text='Ссылка на 2ГИС/Google Maps для кнопки «Как проехать»', verbose_name='Ссылка на карту')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
